import { StyleSheet } from "react-native";
import { verticalUnits } from "../jmecheriis/ddunits";

export const styles = StyleSheet.create({
  experienceSection: {
    display: "flex",
    flexDirection: "row",
    width: "94%",
    paddingHorizontal: "3%",
    paddingVertical: verticalUnits(1.5),
    marginTop: verticalUnits(2),
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
    shadowColor: "#0000000",
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  experienceImage: {
    borderRadius: 10,
    marginRight: "5%",
  },
  experienceName: {
    color: "#000000",
  },
  experienceUsername: {
    color: "#9394a5",
  },
  experienceDate: {
    color: "#9394a5",
    fontSize: 12,
    //marginLeft: "5%",
    width: "80%",
    textAlign: "center",
  },
  experienceDescription: {
    color: "#000000",
  },
  experienceIdentifiers: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "80%",
    marginBottom: "2%",
  },
  container: {
    width: "100%",
    height: "100%",
    color: "white",
  },
  buttonsView: {
    width: "40%",
  },
  button: {
    backgroundColor: "rgba(114, 17, 162, .7)",
  },
  profileTabSection: {
    justifyContent: "space-around",
    width: "100%",
    flexDirection: "row",
    marginTop: "3%",
    height: 50,
  },
  profileTab: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  profileTabText: {
    fontSize: 15,
  },
  inactiveTab: {
    padding: "5%",
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    shadowColor: "#000000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  activeTab: {
    backgroundColor: "rgba(114, 17, 162, .7)",
    borderRadius: 15,
    shadowColor: "#000000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  inactiveTabText: {
    color: "#000000",
  },
  activeTabText: {
    color: "#FFFFFF",
  },
  searchBar: {
    marginTop: "5%",
    marginBottom: "2%",
    backgroundColor: "#FBF2FF",
    borderRadius: 30,
    width: "90%",
    alignSelf: "center",
    padding: 10,
    color: "#7211A2",
    shadowColor: "#C981EC",
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  diplomaSection: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    width: "96%",
    marginTop: "5%",
    marginLeft: "2%",
    marginRight: "2%",
    paddingLeft: "5%",
    paddingVertical: "4%",
    paddingRight: "1%",
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
    shadowColor: "#0000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  editExperienceText: {
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: "5%",
  },
  editExperienceButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  addButton: {
    position: "absolute",
    bottom: "4%",
    right: "8%",
    aspectRatio: 1,
    width: "15%",
    borderRadius: 100,
    backgroundColor: "#7211A2",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
  },

  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: verticalUnits(10),
    marginTop: verticalUnits(2),
  },
  modalView: {
    backgroundColor: "white",
    borderRadius: 20,
    height: "90%",
    width: "90%",
    shadowColor: "#000",
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    padding: "5%",
    paddingTop: verticalUnits(3),
    display: "flex",
  },
  modalViewContainerStyle: {
    justifyContent: "space-between",
    alignItems: "center",
  },
  buttonOpen: {
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
  },
  modalTextInput: {
    width: "100%",
    height: verticalUnits(6),
    marginBottom: verticalUnits(3),
    minHeight: "6%",
    borderRadius: 15,
    paddingLeft: 10,
    backgroundColor: "#f6f6f6",
  },
  modalDescription: {
    width: "100%",
    height: "21%",
    minHeight: "21%",
    borderRadius: 15,
    paddingLeft: "5%",
    paddingRight: "5%",
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: "#f6f6f6",
    textAlignVertical: "top",
    marginBottom: verticalUnits(3)
  },
  modalDate: {
    width: "45%",
    height: "100%",
    backgroundColor: "#f6f6f6",
    textAlign: "center",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    borderRadius: 15,
  },
  intervalPressable: {
    width: "45%",
    height: "100%",
    backgroundColor: "#f6f6f6",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 15,
  },
  setIntervalText: {
    color: "#cfcfcf",
  },
  unsetIntervalText: {
    color: "#000000",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  uploadImageButton: {
    width: "100%",
    height: verticalUnits(15), 
    marginBottom: verticalUnits(3),
    backgroundColor: "#f6f6f6",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 15,
  },
  uploadIcon: {
    fontSize: 40,
    color: "#cfcfcf",
  },
  submitButton: {
    backgroundColor: "#7211A2",
    paddingVertical: "3%",
    paddingHorizontal: "15%",
    borderRadius: 15,
    marginBottom: verticalUnits(18),
  },
  deleteButton: {
    backgroundColor: "#ff0000",
    paddingVertical: "3%",
    paddingHorizontal: "15%",
    borderRadius: 15,
    marginBottom: verticalUnits(18),
  },
  modalText: {
    fontSize: 16,
    fontWeight: "normal",
    marginBottom: verticalUnits(6),
    textAlign: "center",
  },
  attestedText: {
    marginTop: verticalUnits(1),
    color: "rgba(114, 17, 162, .7)",
    fontStyle: "italic",
  },
});

