import { StyleSheet, Platform } from "react-native";
import { verticalUnits } from "../jmecheriis/ddunits";

export const styles = StyleSheet.create({
  profileStatsSection: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
  },
  profileStatsSubsection: {
    display: "flex",
    flexDirection: "column",
    width: "33%",
    marginBottom: verticalUnits(1),
  },
  profileStatsSubsectionText: {
    color: "#000000",
    fontWeight: "600",
    fontSize: 20,
    textAlign: "center",
    flexWrap: "wrap",
  },
  profileStatsSubsectionTextV2: {
    color: "rgba(114, 17, 162, .7)",
    fontWeight: "800",
    fontSize: 14,
    textAlign: "center",
    flexWrap: "wrap",
  },
  profileStatsSubsectionTextV3: {
    color: "#000000",
    fontWeight: "800",
    fontSize: 14,
    textAlign: "center",
    flexWrap: "wrap",
  },
  profileStatsSubsectionTextV4: {
    color: "rgba(114, 17, 162, .7)",
    fontWeight: "600",
    fontSize: 20,
    textAlign: "center",
    flexWrap: "wrap",
  },
  profilePicture: {
    width: "100%",
    height: "100%",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "5%",
  },
  circlePfp: {
    backgroundColor: "rgba(114, 17, 162, .7)",
    aspectRatio: 1,
    position: "absolute",
    height: verticalUnits(15),
    width: "100%",
    top: 0,
    left: 0,
  },
  containerPfp: {
    shadowColor: "rgba(114, 17, 162, .7)",
    elevation: 20,
    marginBottom: "5%",
    borderRadius: 100,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: "45%",
    aspectRatio: 1,
  },
  profileTopSection: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    paddingTop: "10%",
    width: "100%",
    paddingLeft: "5%",
    paddingRight: "5%",
  },
  profileButtonSection: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-evenly",
    paddingTop: "5%",
    width: "100%",
    paddingLeft: "5%",
    paddingRight: "5%",
  },
  topProfileButton: {
    width: "90%",
    margin: "auto",
    marginLeft: "5%",

    paddingTop: "6%",
    paddingBottom: "6%",

    textAlign: "center",
    borderRadius: 15,
    color: "#FFFFFF",
    backgroundColor: "rgba(114, 17, 162, .7)",
    fontWeight: "400",
  },
  profileTabSection: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    marginTop: "8%",
    height: 50,
    borderTopWidth: 1,
    borderBottomWidth: 1,
  },
  profileTab: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  profileTabText: {
    fontSize: 15,
  },
  inactiveTab: {
    backgroundColor: "#FFFFFF",
  },
  activeTab: {
    backgroundColor: "#000000",
  },
  inactiveTabText: {
    color: "#000000",
  },
  activeTabText: {
    color: "#FFFFFF",
  },
  profileInfoSection: {
    marginTop: verticalUnits(3.5),
    paddingBottom: verticalUnits(3),
    paddingHorizontal: "8%",
    width: "100%",
  },
  name: {
    color: "#000000",
    fontWeight: "600",
    marginRight: "2%",
    fontSize: 16,
    textAlignVertical: "center",
  },
  username: {
    color: "#9394a5",
    textAlignVertical: "center",
  },
  description: {
    color: "#000000",
  },
  identificationData: {
    display: "flex",
    justifyContent: "flex-start",
    flexDirection: "row",
    marginBottom: verticalUnits(1),
  },
  experienceSection: {
    display: "flex",
    flexDirection: "row",
    width: "94%",
    paddingHorizontal: "3%",
    paddingVertical: verticalUnits(1.5),
    marginTop: verticalUnits(2),
    borderRadius: 15,
    backgroundColor: "#FFFFFF",
    shadowColor: "#0000000",
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  experienceImage: {
    borderRadius: 10,
    marginRight: "5%",
    marginBottom: "12%",
  },
  experienceName: {
    color: "#000000",
    fontWeight: 500,
  },
  experienceLocation: {
    color: "#9394a5",
  },
  experienceDate: {
    color: "#9394a5",
    fontSize: 12,
    //marginLeft: "5%",
    width: "80%",
    textAlign: "center",
  },
  experienceDescription: {
    color: "#000000",
    fontWeight: 400,
  },
  experienceIdentifiers: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "80%",
    marginBottom: "2%",
  },
  diplomaSection: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
    padding: "5%",
    borderTopWidth: 0.2,
    borderBottomWidth: 0.2,
  },
  recentEventText: {
    fontSize: 24,
    fontWeight: "semibold",
    marginLeft: "3%",
  },
  seeAllText: {
    fontWeight: "800",
    textDecorationLine: "underline",
    marginLeft: "3%",
    marginTop: "2%",
    color: "rgba(114, 17, 162, .8)",
  },
  icon: {
    fontSize: 20,
    paddingHorizontal: "1%",
  },
  header: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingLeft: "4%",
    paddingRight: "6%",
    backgroundColor: "#ffffff",
    height: verticalUnits(6),
    //paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0, // Adjusts for the status bar on Android
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "bold",
    paddingLeft: "3%",
  },
  backIcon: {
    fontSize: 30,
  },
  attestedText: {
    marginTop: verticalUnits(1),
    color: "rgba(114, 17, 162, .7)",
    fontStyle: "italic",
  },
  placeholderText:{
    color: "#9394a5",
    marginTop: verticalUnits(12),
    fontSize: 16,
  }
});

